version: 2

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true
  builder: dirhtml

formats:
  - pdf
  - epub

python:
  version: 3
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
