blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: https://github.com/adamghill/django-fbv/discussions/new
    about: Submit a bug or an issue
  - name: Feature request
    url: https://github.com/adamghill/django-fbv/discussions/new
    about: For ideas or feature requests
  - name: Support questions & other
    url: https://github.com/adamghill/django-fbv/discussions/new
    about: If you have a question or need help using the library
  - name: Documentation issue
    url: https://github.com/adamghill/django-fbv/discussions/new
    about: For documentation improvements
